#!/usr/bin/env python3
"""Build the Muse-optimized skill package from the canonical plugin sources.

The plugin under plugins/lastmilefirst/ is the single source of truth.
This script applies adapters/muse/mapping.toml (mechanism translations only) and
emits adapters/muse/dist/skills/lastmilefirst/. Nothing is duplicated by hand:
either a file is generated by this script, or it is hand-written adapter
prose that contains no canonical content.

dist/ is gitignored by design: it is built at install time, never committed.

Usage:
    python3 adapters/muse/build.py           # regenerate dist/
    python3 adapters/muse/build.py --check   # exit 1 if dist/ is stale (freshness)
    python3 adapters/muse/build.py --lint    # exit 1 on leftover Claude Code-isms
                                    # (slash commands, product names) in
                                    # built output. Fenced code blocks are
                                    # examples and are skipped.

Only the standard library is used, so the only requirement is python3.
"""

import re
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
MUSE_DIR = REPO / "adapters" / "muse"
DIST_SKILL = MUSE_DIR / "dist" / "skills" / "lastmilefirst"

HEADER = """> Generated from [{source}]({source}) by `adapters/muse/build.py`. Do not edit by hand.
> Translation table: `adapters/muse/mapping.toml`. Re-run the build to pick up changes.

"""

def load_mapping() -> dict:
    with open(MUSE_DIR / "mapping.toml", "rb") as f:
        return tomllib.load(f)


def strip_frontmatter(text: str) -> str:
    """Remove a leading YAML frontmatter block delimited by --- lines."""
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            return text[end + len("\n---") :].lstrip("\n")
    return text


def apply_mapping(text: str, replacements: list[dict]) -> str:
    """Apply replacements longest-first, including inside fenced code blocks.

    A `/run-foo` inside a fence is mechanism, not verbatim scripture: leaving
    it untranslated would hand the Muse agent a command that does not exist
    there. The mapping renders the real Muse equivalent instead (a script
    invocation, a skill-phase reference, or prose).
    """
    repls = sorted(replacements, key=lambda r: len(r["pattern"]), reverse=True)
    for r in repls:
        text = text.replace(r["pattern"], r["replacement"])
    # A replacement that adds its own backticks can land inside an already
    # backticked span (`` `/run-foo` `` -> ``` `` `bin/foo` `` ```). Collapse
    # exactly-double backticks; fence markers (```) are left alone.
    text = re.sub(r"(?<!`)``(?!`)", "`", text)
    return text


def build_persona_roster(mapping: dict) -> str:
    """Index of canonical persona files. One-liners go through the mapping."""
    cfg = mapping["persona_roster"]
    replacements = mapping["replacements"]
    src_dir = REPO / cfg["source_dir"]
    lines = [
        HEADER.format(source=cfg["source_dir"] + "/*.md"),
        "# Expert Personas (roster)",
        "",
        "To consult an expert: `subagent.spawn` a subagent briefed with the persona file. "
        "Give it role, context, task, constraints, and success criteria; it reports back.",
        "",
    ]
    for path in sorted(src_dir.glob("*.md")):
        text = path.read_text()
        title = next((l[2:] for l in text.splitlines() if l.startswith("# ")), path.stem)
        # First sentence of the opening paragraph as the one-liner, translated.
        body = strip_frontmatter(text)
        para = next((b for b in body.split("\n\n") if b.strip() and not b.startswith("#")), "")
        one_liner = para.replace("\n", " ").split(". ")[0].strip()
        if one_liner and not one_liner.endswith("."):
            one_liner += "."
        one_liner = apply_mapping(one_liner, replacements)
        lines.append(f"- **{title}**: `{path.relative_to(REPO)}`")
        if one_liner:
            lines.append(f"  {one_liner}")
    return "\n".join(lines) + "\n"


def build() -> dict[str, str]:
    """Returns {output_relpath: rendered_text} without writing."""
    mapping = load_mapping()
    replacements = mapping["replacements"]
    outputs: dict[str, str] = {}
    for src in mapping["sources"]:
        canonical = (REPO / src["source"]).read_text()
        body = strip_frontmatter(canonical)
        body = apply_mapping(body, replacements)
        outputs[src["output"]] = HEADER.format(source=src["source"]) + body
    outputs[mapping["persona_roster"]["output"]] = build_persona_roster(mapping)
    # Hand-written adapter files (the Muse-specific design) copy verbatim.
    # They contain no canonical content, so there is nothing to drift.
    adapter = MUSE_DIR / "adapter" / "skills" / "lastmilefirst"
    for path in sorted(adapter.rglob("*")):
        if path.is_file():
            outputs[str(path.relative_to(adapter))] = path.read_text()
    return outputs


# --- lint: the freshness check proves the output matches the sources;
#     this proves the output is right. ---
SLASH_RE = re.compile(r"/(?:run|reload)-[a-z][a-z0-9-]*")
PRODUCT_NAMES = ["Claude Code"]
# Proper nouns that legitimately name the product (persona name, file name,
# provenance note) rather than invoking its machinery.
PRODUCT_ALLOW = [
    "Shannon the Claude Code Expert",
    "shannon-claude-code-expert.md",
    "Ported from the GruntworkAI LastMileFirst Claude Code",
]


def lint(outputs: dict[str, str]) -> list[str]:
    problems: list[str] = []
    for rel, text in outputs.items():
        for m in SLASH_RE.finditer(text):
            lineno = text.count("\n", 0, m.start()) + 1
            problems.append(f"{rel}:{lineno}: leftover slash command {m.group()}")
        for lineno, line in enumerate(text.splitlines(), 1):
            for name in PRODUCT_NAMES:
                if name in line and not any(a in line for a in PRODUCT_ALLOW):
                    problems.append(f'{rel}:{lineno}: leftover product name "{name}"')
    return problems


def main() -> int:
    if "--lint" in sys.argv:
        problems = lint(build())
        if problems:
            print("LINT failures (leftover Claude Code-isms in built output):")
            for p in problems:
                print(f"  - {p}")
            return 1
        print("lint clean.")
        return 0

    check_only = "--check" in sys.argv
    outputs = build()
    stale: list[str] = []
    for rel, text in outputs.items():
        dest = DIST_SKILL / rel
        if not dest.exists() or dest.read_text() != text:
            stale.append(rel)
            if not check_only:
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_text(text)
                print(f"wrote {dest.relative_to(REPO)}")
    if check_only:
        if stale:
            print("STALE generated files (run adapters/muse/build.py):")
            for rel in stale:
                print(f"  - dist/skills/lastmilefirst/{rel}")
            return 1
        print("dist/ is fresh.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
